#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v13
# autospec commit: dc0ff31
#
Name     : libwps
Version  : 0.4.2
Release  : 6
URL      : https://dev-www.libreoffice.org/src/libwps-0.4.2.tar.bz2
Source0  : https://dev-www.libreoffice.org/src/libwps-0.4.2.tar.bz2
Summary  : A library for reading Microsoft Works word processor documents
Group    : Development/Tools
License  : LGPL-2.1 MPL-2.0-no-copyleft-exception
Requires: libwps-bin = %{version}-%{release}
Requires: libwps-lib = %{version}-%{release}
Requires: libwps-license = %{version}-%{release}
BuildRequires : boost-dev
BuildRequires : buildreq-configure
BuildRequires : doxygen
BuildRequires : pkgconfig(librevenge-0.0)
BuildRequires : pkgconfig(librevenge-generators-0.0)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
INSTALLATION
General
=======
Since libwps was based on librevenge code (for convenience), you need to install
librevenge in order to build libwps. You can get librevenge from:

%package bin
Summary: bin components for the libwps package.
Group: Binaries
Requires: libwps-license = %{version}-%{release}

%description bin
bin components for the libwps package.


%package dev
Summary: dev components for the libwps package.
Group: Development
Requires: libwps-lib = %{version}-%{release}
Requires: libwps-bin = %{version}-%{release}
Provides: libwps-devel = %{version}-%{release}
Requires: libwps = %{version}-%{release}

%description dev
dev components for the libwps package.


%package doc
Summary: doc components for the libwps package.
Group: Documentation

%description doc
doc components for the libwps package.


%package lib
Summary: lib components for the libwps package.
Group: Libraries
Requires: libwps-license = %{version}-%{release}

%description lib
lib components for the libwps package.


%package license
Summary: license components for the libwps package.
Group: Default

%description license
license components for the libwps package.


%prep
%setup -q -n libwps-0.4.2
cd %{_builddir}/libwps-0.4.2
pushd ..
cp -a libwps-0.4.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719972290
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1719972290
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libwps
cp %{_builddir}/libwps-%{version}/COPYING.LGPL %{buildroot}/usr/share/package-licenses/libwps/3704f4680301a60004b20f94e0b5b8c7ff1484a9 || :
cp %{_builddir}/libwps-%{version}/COPYING.MPL %{buildroot}/usr/share/package-licenses/libwps/9744cedce099f727b327cd9913a1fdc58a7f5599 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/wks2csv
/V3/usr/bin/wks2raw
/V3/usr/bin/wks2text
/V3/usr/bin/wps2html
/V3/usr/bin/wps2raw
/V3/usr/bin/wps2text
/usr/bin/wks2csv
/usr/bin/wks2raw
/usr/bin/wks2text
/usr/bin/wps2html
/usr/bin/wps2raw
/usr/bin/wps2text

%files dev
%defattr(-,root,root,-)
/usr/include/libwps-0.4/libwps/WPSDocument.h
/usr/include/libwps-0.4/libwps/libwps.h
/usr/lib64/libwps-0.4.so
/usr/lib64/pkgconfig/libwps-0.4.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/libwps/*

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libwps-0.4.so.4.0.2
/usr/lib64/libwps-0.4.so.4
/usr/lib64/libwps-0.4.so.4.0.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libwps/3704f4680301a60004b20f94e0b5b8c7ff1484a9
/usr/share/package-licenses/libwps/9744cedce099f727b327cd9913a1fdc58a7f5599
